server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.41.230.125:3306/activiti_demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Guan123,.

# activiti配置
  activiti:
    database-schema-update: true  # 自动更新数据库
    db-history-used: true   # 启用历史表
    history-level: audit  # 历史记录级别

logging:
  config: classpath:logback-spring.xml

mybatis:
  mapper-locations: classpath:mapper/*.xml